package com.ludimosdemo.models

data class BallTrackResponse(
    val ai_status: String,
    val archived: Boolean,
    val ball_track_status: String,
    val created_at: String,
    val deleted: Boolean,
    val description: Any,
    val duration: Double,
    val exclude_from_dataset: Boolean,
    val fps: Double,
    val height: Int,
    val id: Int,
    val motion_detected: Boolean,
    val original_url: String,
    val pose_status: String,
    val rotation: Int,
    val size: Double,
    val source_url: String,
    val status: String,
    val stump_line: List<Double>,
    val stump_loc_3d: Any,
    val stumpline_status: String,
    val team_id: Int,
    val thumbnail_url: String,
    val title: String,
    val training_date: String,
    val training_session_id: Int,
    val updated_at: String,
    val uploaded_by: Int,
    val user_id: Int,
    val video_type: String,
    val width: Int
)